PrestaShopCorp/puik

packages/theme/src/button.scss
packages/theme/src/common/typography.scss

Fix the alignement of icons inside Button
Set fixed height for button to fix border overflow and icon displacement
https://www.notion.so/prestashopcorp/Icons-on-buttons-are-not-aligned-add7359139fa47c8bd4d1b290a45dd73

fix: icon alignement in button

---

docs/.storybook/preview.js
packages/components/spinner-loader/stories/spinner-loader.stories.ts

Spinner loader snapshot are always updated due to the animation, add option to pause it.

fix: add animation pause on chromatic snapshot

---

packages/components/tooltip/src/tooltip.ts

Revert popperJS type import to litteral string to avoid commonjs error while using puik

fix: error while importing popperjs type

---

packages/components/menu/src/menu.vue
packages/components/menu/stories/menu.stories.ts

Adding open state of the menu to slop props

[Feature]: add menu open state to slot props

---

packages/theme/src/common/typography.scss

This PR aims to change the PuikButton font weight from semibold (600) to medium (500) to match with the PuikButton in figma

Fix: Use correct font-weight for the PuikButton component

---

packages/theme/src/sidebar-item.scss

fix scss file for displaying active state of sidebar item component
fix puik-sidebar-item--active scss class

fix: (issue #159) sidebar-item active state (fix scss class)

---

packages/theme/src/tooltip.scss

remove css transition (conflict when use disappearDelay prop )

fix: #219 - tootlip - remove transition-opacity

---

packages/components/link/src/link.ts
packages/components/link/src/link.vue
packages/theme/src/link.scss

fix : [BUG] puik link decoration underline is fucked up on multi-line 😭 + width 100% not good #232

fix: #232 : puik-link underline on multi-lines

---

packages/components/alert/src/alert.ts
packages/components/alert/src/alert.vue
packages/components/alert/stories/alert.stories.ts
packages/components/alert/test/alert.spec.ts
packages/theme/src/alert.scss

Added a close button to the Alert component
:warning: We need this feature before the end of this sprint

Feat -  Add close button to alert component

---

packages/components/tab-navigation/stories/tab-navigation.stories.ts
packages/theme/src/tab-navigation-group-titles.scss
packages/theme/src/tab-navigation-title.scss

- Suppression de l'affichage en colonne pour le responsive
- Suppression d'une min-width/width pour les tab title
- Suppression du retour a la ligne des tabs
- Ajout du tips dans le storybook

fix: tab nav remove flex col and the min width

---

packages/components/chip/src/chip.vue
packages/components/chip/test/chip.spec.ts
packages/components/tag/src/tag.vue
packages/components/tag/test/tag.spec.ts
packages/theme/src/chip.scss
packages/theme/src/tag.scss

use isEllipsisIsActive function to trigger tooltip instead of using the length of the content
related issue #225

improvement: [chip/tag] fix #225 - use isEllipsis to trigger tooltip

---

packages/components/accordion/src/accordion.vue
packages/components/accordion/test/accordion.spec.ts
packages/components/alert/src/alert.vue
packages/components/alert/test/alert.spec.ts
packages/components/avatar/src/avatar.vue
packages/components/avatar/test/avatar.spec.ts
packages/components/checkbox/src/checkbox.vue
packages/components/checkbox/test/checkbox.spec.ts
packages/components/input/src/input.vue
packages/components/input/test/input.spec.ts
packages/components/modal/src/modal.vue
packages/components/modal/test/modal.spec.ts
packages/components/pagination/src/pagination.vue
packages/components/pagination/test/pagination.spec.ts
packages/components/progress-bar/src/progress-bar.vue
packages/components/progress-bar/test/progress-bar.spec.ts
packages/components/progress-stepper/src/progress-stepper-step.vue
packages/components/progress-stepper/test/progress-stepper-step.spec.ts
packages/components/radio/src/radio.vue
packages/components/radio/test/radio.spec.ts
packages/components/sidebar/src/sidebar-group-item.vue
packages/components/sidebar/src/sidebar-item.vue
packages/components/sidebar/test/sidebar-group-item.spec.ts
packages/components/sidebar/test/sidebar-item.spec.ts
packages/components/tag/src/tag.vue
packages/components/tag/test/tag.spec.ts
packages/components/tooltip/src/tooltip.vue
packages/components/tooltip/test/tooltip.spec.ts

**breaking changes on data-test attributes**  
Some components present a problem when they have already been used with a data-test attribute before version 1.8. To correct this, I added a data-test (without adding a prefix) to the first parent of the components that I spotted

fix: try to fix first parent who don't have a data-test by default

---

packages/components/table/src/table.ts
packages/components/table/src/table.vue
packages/components/table/stories/table.stories.ts
packages/components/table/test/table.spec.ts
packages/theme/src/table.scss

Table : add sticky columns and expandable rows features
related issues: #249 #250

Table : add sticky columns and expandable rows features

---

packages/components/link/src/link.ts
packages/components/link/src/link.vue
packages/components/link/stories/link.stories.ts
packages/components/link/test/link.spec.ts
packages/theme/src/link.scss

Added a high contrast variant for the PuikLink (this variant disables the link purple when the link has been visited)
We need this feature to finish a task for this sprint

Feat - Add high contrast variant for PuikLink

---

packages/components/snackbar/src/snackbar.vue

Add close event on action-button for the snackbar disappear on click 
[Bug Ticket](https://github.com/PrestaShopCorp/puik/issues/268#event-11191165509)

SnackBar: add close on action-button 

---

package.json
packages/components/select/test/select.spec.ts
packages/components/table/src/table.ts
packages/components/table/src/table.vue
packages/components/table/test/table.spec.ts
playground/package-lock.json
playground/package.json
pnpm-lock.yaml

fix: [Table] #295 data reactivity issue

---

build/package.json
build/src/tasks/full-bundle.ts
build/src/tasks/modules.ts
packages/components/icon/src/icon.ts
packages/components/icon/src/icon.vue
packages/components/icon/stories/icon.stories.ts
packages/components/icon/test/icon.spec.ts
packages/puik/tsconfig.json
packages/tailwind-preset/index.js
packages/tailwind-preset/theme.js
packages/theme/tailwind.config.js
packages/theme/tsconfig.json
pnpm-lock.yaml

Related to [this issue](https://github.com/PrestaShopCorp/puik/issues/213)

feat: add disabled state to icon

---

packages/theme/src/badge.scss

fix: #303 - change badge colors

---

packages/components/breadcrumb/src/breadcrumb.ts
packages/components/breadcrumb/src/breadcrumb.vue
packages/components/breadcrumb/stories/breadcrumb.stories.ts
packages/components/breadcrumb/test/breadcrumb.spec.ts

added the dataItems prop to use in the web-component version
(stingify version of items)

fix: #310 added the dataItems prop to use in the web-component version

---

packages/components/alert/stories/alert.stories.ts
packages/components/tag/src/tag.ts

- Required id in tag: Don't need to set it to make the component works, so don't put it as required
- disabled-border: Fix documentation, props name is disable-border

docs: disable-border props alert in stories + id not required for tag

---

package.json
packages/components/package.json
packages/hooks/package.json
packages/locale/package.json
packages/puik/package.json
packages/tailwind-preset/package.json
packages/theme/package.json
packages/tokens/package.json
packages/utils/package.json

update description key in package.json files

fix: #324 - update description key in package.json files

---

packages/components/alert/src/alert.ts
packages/components/alert/src/alert.vue
packages/components/alert/stories/alert.stories.ts
packages/components/alert/test/alert.spec.ts
packages/theme/src/alert.scss

Add link next to the button on the Alert component
ZeroHeight doc: https://zeroheight.com/34f250d18/p/961fa5-alert-banner/b/28d7f7

feat: [SPEX-1952][V1] Add link on Alert component

---

packages/components/alert/src/alert.ts
packages/components/alert/src/alert.vue
packages/components/alert/stories/alert.stories.ts
packages/components/alert/style/css.ts
packages/components/alert/test/alert.spec.ts
packages/theme/src/puik-alert.scss

Add link next to the button on the Alert component
ZeroHeight doc: https://zeroheight.com/34f250d18/p/961fa5-alert-banner/b/28d7f7
****

feat: [SPEX-1952][V2] Add link on Alert component

---

docs/CHANGELOG.md
docs/package.json
packages/components/CHANGELOG.md
packages/components/package.json
packages/puik/CHANGELOG.md
packages/puik/package.json
packages/resolver/CHANGELOG.md
packages/resolver/package.json
packages/tailwind-preset/CHANGELOG.md
packages/tailwind-preset/package.json
packages/theme/CHANGELOG.md
packages/theme/package.json
packages/web-components/CHANGELOG.md
packages/web-components/package.json

prestashopcorp/puik-components` 2.0.0 -> 2.0.1`
prestashopcorp/puik-web-components `2.0.0 -> 2.0.1`
prestashopcorp/puik-resolver `2.0.0 -> 2.0.1`
prestashopcorp/puik-theme `2.0.0 -> 2.0.1`
prestashopcorp/puik-tailwind-preset `2.0.0 -> 2.0.1`
prestashopcorop/puik-docs `1.1.0 -> 1.1.1`

chore: versions bumped

---

packages/components/pagination/src/pagination-large.ts
packages/components/pagination/src/pagination-large.vue
packages/components/pagination/src/pagination-medium.ts
packages/components/pagination/src/pagination-medium.vue
packages/components/pagination/src/pagination.ts
packages/components/pagination/src/pagination.vue
packages/components/pagination/stories/pagination.stories.ts
packages/components/pagination/test/pagination.spec.ts

- handle items count internally (remove prop itemCount and retrieve items count from a computed function instead )
- handle disabled Load More btn internally (remove loaderButtonDisabled prop )

feat: related #344 - handle items count and loader btn behaviors internally

---

packages/components/pagination/src/pagination-large.ts
packages/components/pagination/src/pagination-large.vue
packages/components/pagination/src/pagination-medium.ts
packages/components/pagination/src/pagination-medium.vue
packages/components/pagination/src/pagination-small.ts
packages/components/pagination/src/pagination-small.vue
packages/components/pagination/src/pagination.ts
packages/components/pagination/src/pagination.vue
packages/components/pagination/stories/pagination.stories.ts
packages/components/pagination/test/pagination.spec.ts
packages/locale/lang/en.ts
packages/locale/lang/fr.ts
packages/theme/src/puik-pagination.scss

fix #275 : 
- news props to display results label and items per page select.
- create a label for items per page select
- fix: Implement a watch function for currentPage that triggers when maxPage changes (this occurs when the number of items per page is modified).
- [] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

275 pagination large items per page should be hidden if not specified

---

packages/components/sortable-list/stories/sortable-list.stories.ts

docs: [sortable-list] fix #376 - update shared option story

---

RELEASE-NOTES-V2.md
commitlint.config.cjs
packages/components/alert/src/alert.ts
packages/components/alert/src/alert.vue
packages/components/alert/stories/alert.stories.ts
packages/components/alert/test/alert.spec.ts
packages/theme/src/puik-alert.scss

:warning: fix alert design specs:  by replacing the link (puik-link) by a Link Button (text variant)
:warning:  Finally no action slot to limit BC
News optional props ([see updated stories for use](https://6267e986619a13004a943d93-ukpnjsokhl.chromatic.com/?path=/docs/components-alert--docs)) :
related to Action Button: `rightIconBtn`, `leftIconBtn`, `AriaLabelBtn`
related to Link Button: `internalLink`,  `externalLink` , `rightIconLink`,  `leftIconLink`,  `AriaLabelLink`

feat: [puik-alert] fix #339 - fix alert design specs (link button text), ability to add icons for buttons (Action and Link)

---

playground/.gitignore

ignore vue-app and vanilla-app until #399 is fixed

chore: [gitignore] - fix #400

---

docs/stories/docs/TailwindPreset.mdx
packages/components/skeleton-loader/src/skeleton-loader.vue
packages/theme/src/puik-skeleton-loader.scss

Replace Material Icons by Material Symbols class for Skeleton component (fix #395)

fix: [Skeleton] #395 - display icons for img/video/graph variants

---

packages/components/pagination/src/pagination-large.vue
packages/components/table/src/table.ts
packages/components/table/src/table.vue
packages/components/table/test/table.spec.ts

feat: adding data-test attribute

---

packages/components/button/src/button.ts
packages/components/button/src/button.vue
packages/components/button/stories/button.stories.ts
packages/components/button/style/css.ts
packages/components/button/style/index.ts
packages/components/button/test/button.spec.ts

- new props (`loading` and `loaderPosition`)
- update stories and tests

332 feature button add spinner

---

packages/components/select/src/select.vue
packages/theme/src/puik-select.scss

feat: [Select] - fix bug #412 - review disabled behavior

---

packages/components/tooltip/src/tooltip.vue
packages/components/tooltip/stories/tooltip.stories.ts
packages/components/tooltip/test/tooltip.spec.ts

fix: [tooltip] related  #451 - refato max-width prop

---

packages/components/sortable-list/src/sortable-list.vue

Fix https://github.com/PrestaShopCorp/puik/issues/480
Cannot install PUIK 2.6.0 because of this error: 
```
import { Sortable as K } from "sortablejs-vue3";
^^^^^^^^
```

fix: sortablejs-vue3 import
