PrestaShopCorp/puik

- packages/components/spinner-loader/src/spinner-loader.vue
> fix: spinner loader chromatic snapshot

- packages/components/modal/src/modal.ts
- packages/components/modal/src/modal.vue
- packages/components/modal/stories/modal.stories.ts
- packages/components/modal/test/modal.spec.ts
- packages/theme/src/modal.scss
> [Feature] Modal: set width full on mobile and add hide header prop

- packages/theme/src/menu.scss
> [Fix]: menu zindex

- packages/components/select/src/option.vue
- packages/components/select/src/select.ts
- packages/components/select/src/select.vue
- packages/components/select/stories/select.stories.ts
- packages/components/select/test/select.spec.ts
- packages/theme/src/select.scss
> feat: improve select & option components

- packages/theme/src/select.scss
- [N/A] My change requires a change to the documentation.
- [N/A] I have updated the documentation accordingly.
- [N/A] I have added tests to cover my changes
- [N/A] The component exists on old Prestashop UIKit and my pull request on [migrating documentation](https://github.com/PrestaShopCorp/devdocs.uikit.prestashop.com) is accepted.
> fix: change color of disabled select

- packages/components/button/src/button.ts
- packages/components/sidebar/src/sidebar-item.ts
add type RouteLocationRaw for prop "to"
> fix: (issue #165) add type RouteLocationRaw for prop "to"

- README.md
- packages/tailwind-preset/package.json
- packages/theme/src/button.scss
- packages/theme/tailwind.config.js
Use Tailwind darkMode, actually I made a setup for the example.
- If we wanna use the OS/browser preference we need to remove the `darkMode` line in the `theme/tailwind.config.js`
- I added dark mode rules for the button but it is just an example with random value ⚠️
> feat: use tailwind darkmode

- packages/components/breadcrumb/src/breadcrumb.ts
add RouteLocationRaw type for the prop "to"
> fix:  #180 -  add Location type for the prop "to"

- packages/components/card/src/card.ts
- packages/components/card/stories/card.stories.ts
- packages/theme/src/card.scss
Puik-card : add green variant
add green variant
> fix: #167 - add green variant

- packages/components/icon/src/icon.vue
- packages/theme/src/breadcrumb.scss
- packages/theme/src/link.scss
change style : link color
https://forge.prestashop.com/browse/VAL-297
> fix: #216 - link color

- packages/theme/src/link.scss
css : change direction for underline animation
> style: [link] - fix #218 - change direction for underline animation

- packages/components/icon/index.ts
- packages/components/tooltip/index.ts
- packages/puik/component.ts
- playground/vite.config.ts
> fix: remove icon and tooltip ce

- packages/components/snackbar/src/notify.ts
- packages/components/snackbar/src/snackbar.ts
- packages/components/snackbar/src/snackbar.vue
- packages/components/snackbar/stories/snackbar-use.stories.mdx
- packages/components/snackbar/stories/snackbar.stories.ts
- packages/components/snackbar/test/snackbar.spec.ts
That issue => https://github.com/PrestaShopCorp/puik/issues/158
> fix: update snackbar behavior -> remove stackable behavior

- packages/theme/src/option.scss
- packages/theme/src/select.scss
Update select component
[That Issue](https://github.com/PrestaShopCorp/puik/issues/198) + remove rounded corner (options) + options width + put text options on left
> fix: fix some issues with select component

- packages/theme/src/accordion-group.scss
- packages/theme/src/accordion.scss
[To Fix this ISSUE](https://github.com/PrestaShopCorp/puik/issues/237)
Use flex + flex gap instead of margin
> fix: remove margin and add gap

- packages/components/tab-navigation/src/tab-navigation-title.ts
- packages/theme/src/tab-navigation-group-titles.scss
- packages/theme/src/tab-navigation-title.scss
- Add responsive behavior: column on small screen (>640px) + carriage return on bigger screen
- Refacto CSS to use tailwind
> feat: improve tab nav responsivity

- docs/stories/styles/Typography.stories.ts
- packages/tailwind-preset/theme.js
- packages/theme/src/common/typography.scss
> fix: #251 - typography tokens

- packages/components/chip/src/chip.ts
- packages/components/modal/src/modal.vue
- packages/theme/src/chip.scss
- packages/theme/src/icon.scss
- packages/theme/src/modal.scss
Add style to icon 
[Bug Ticket](https://github.com/PrestaShopCorp/puik/issues/269#event-11191161862)
Before:
After:
> fix: Icon on modal

- packages/components/accordion/src/accordion.ts
- packages/components/accordion/src/accordion.vue
- packages/components/accordion/stories/accordion.stories.ts
- packages/components/accordion/test/accordion.spec.ts
- packages/theme/src/accordion.scss
fix #292 :  new prop border-none
> fix: [accordion] #292 new prop border-none

- packages/theme/src/switch.scss
fix #290  switch : update size
> fix: [switch] #290  update size

- packages/components/alert/src/alert.ts
> fix: [alert]  #288 try to fix duplicate identifier error

- packages/components/snackbar/stories/snackbar-use.stories.mdx
- packages/components/table-search-input/style/css.ts
- packages/components/table-search-input/style/index.ts
- packages/components/table/src/table-search-input.vue
- packages/components/table/src/table.vue
- packages/components/table/style/css.ts
- packages/components/table/style/index.ts
- packages/puik/component.ts
- packages/theme/src/input.scss
- packages/theme/src/table-search-input.scss
- typings/global.d.ts
> fix: [table] #300 PuikInputSearch style does not apply

- packages/components/link/src/link.ts
- packages/components/link/src/link.vue
- packages/components/link/stories/link.stories.ts
- packages/components/link/test/link.spec.ts
- packages/theme/src/link.scss
Articles props added
New feature: https://www.figma.com/file/YxI7gWKwOKc0QGMvaTal8j/PrestaShop-Core-Design-Kit?type=design&node-id=18992-20121&mode=dev
> feat: articles variant added to link component

- package.json
- packages/components/table/src/table.vue
- packages/components/table/stories/table.stories.ts
- playground/package.json
- pnpm-lock.yaml
- update storybook for table component
> fix: #304 update storybook

- build/package.json
- build/src/tasks/full-bundle.ts
- build/src/tasks/modules.ts
- packages/components/icon/src/icon.vue
- packages/components/icon/test/icon.spec.ts
- packages/puik/tsconfig.json
- packages/tailwind-preset/index.js
- packages/tailwind-preset/theme.js
- packages/theme/src/icon.scss
- packages/theme/tailwind.config.js
- packages/theme/tsconfig.json
- playground/.gitignore
- pnpm-lock.yaml
hotfix release v1.12.0:
- rollback rollup config
- rollback theme and taiwind config
- update icon disabled feature
- update icon test
> Fix rollup config

- packages/components/input/src/input.vue
J'ai ajouté l'héritage des attributs sur le champ input
J'ai besoin d'avoir le controle du focus sur ce composant dans mon projet
> feat: Attribute Inheritance added to input component

- packages/components/notification-bar/src/notification-bar.vue
- packages/components/notification-bar/stories/notification-bar.stories.ts
- packages/theme/src/notification-bar.scss
fix #312
when scrolling horizontally the messages appear in bg of the close
update storybook
> fix: #312 - notification-bar -  update style and docs

- packages/theme/src/modal.scss
> PACC-1813/fix/responsive modale

- .github/workflows/cd-publish-package.yml
- [X ] 👌 Enhancement (improving an existing functionality)
Change CI to publish packages with tag "beta" in case of tag including "-beta" to avoid to mark it as "latest"
Need feat/2.0.0-beta branch
> feat(ci): Publish beta version with tag "beta" instead "latest"

- .vscode/settings.json
- packages/components/table/src/table.vue
- packages/theme/package.json
- packages/theme/src/puik-table.scss
- packages/theme/tailwind.config.js
- playground/tailwind.config.js
- pnpm-lock.yaml
fix #340 :
- sticky header
- max-height for long table
- remove tailwind-scrollbar plugin
> feat: [Table] fix #340 - sticky header, max-height for long table, remove tailwind-scrollbar plugin

- packages/components/pagination/src/pagination-large.vue
pagination large variant : 
update jumper pagination value when changing pages
> fix: #342 - update jumper pagination value when changing pages

- packages/components/config-provider/src/config-provider-props.ts
- packages/components/config-provider/stories/config-provider.stories.ts
- packages/locale/lang/fr.ts
- Doc: [Storybook] create doc for PuikConfigProvider
- Update fr translations
> docs: [Storybook][PuikConfigProvider] - fix #350 - create doc + update fr translations

- packages/components/avatar/stories/avatar.stories.ts
Avatar photo variant : change src img  in storybook (static img to prevent rerunning UI test for each chromatic build)
> docs: [Avatar-Storybook] - fix #356

- docs/CHANGELOG.md
- docs/package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/locale/CHANGELOG.md
- packages/locale/package.json
- packages/puik/CHANGELOG.md
- packages/puik/package.json
- packages/resolver/CHANGELOG.md
- packages/resolver/package.json
- packages/tailwind-preset/CHANGELOG.md
- packages/tailwind-preset/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package.json
bump versions packages (puik v2.1.0)
> chore: bump versions packages (puik v2.1.0)

- packages/theme/src/puik-sidebar.scss
fix #371 - reduced line-height of expand/collapse btn header icon
> [sidebar] fix #371 - reduced line-height of expand/collapse btn header icon

- packages/components/LICENSE
- packages/components/package.json
- packages/locale/LICENSE
- packages/puik/LICENSE
- packages/puik/package.json
- packages/resolver/LICENSE
- packages/resolver/package.json
- packages/tailwind-preset/LICENSE
- packages/theme/LICENSE
- packages/utils/LICENSE
- packages/web-components/LICENSE
- packages/web-components/package.json
- pnpm-lock.yaml
> 374 chore update dependencies and add licences for each package

- playground/README.md
> docs: update readme

- docs/CHANGELOG.md
- docs/package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/locale/CHANGELOG.md
- packages/locale/package.json
- packages/puik/CHANGELOG.md
- packages/puik/package.json
- packages/resolver/CHANGELOG.md
- packages/resolver/package.json
- packages/tailwind-preset/CHANGELOG.md
- packages/tailwind-preset/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/utils/CHANGELOG.md
- packages/utils/package.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package.json
bumped versions packages for release v2.2.0
> chore: fix #378 - bumped versions packages for release v2.2.0

- .github/workflows/chromatic.yml
- .github/workflows/ci.yml
- upgrade node  version 18 to 20
- uprade some actions versions
> ci: [chromatic-workflow] - related #388 : upgrade chromatic workflow

- docs/CHANGELOG.md
- docs/package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/puik/CHANGELOG.md
- packages/puik/package.json
- packages/tailwind-preset/CHANGELOG.md
- packages/tailwind-preset/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package.json
> chore: bumped versions packages for release v2.3.0

- packages/components/snackbar/index.ts
- packages/components/snackbar/src/snackbar.ts
- packages/components/snackbar/src/snackbar.vue
- packages/components/snackbar/src/use-snackbar.ts
- packages/components/snackbar/stories/snackbar.stories.ts
- packages/components/snackbar/test/snackbar.spec.ts
> feature [snackbar] create snackbar programmatically (useSnackbar function)

- packages/components/tab-navigation/src/tab-navigation-group-titles.vue
- packages/components/tab-navigation/src/tab-navigation.ts
- packages/components/tab-navigation/src/tab-navigation.vue
- packages/components/tab-navigation/stories/tab-navigation.stories.ts
- packages/components/tab-navigation/test/tab-navigation.spec.ts
fix #404 - create change-active-tab event.
> [tab navigation] create an event to detect the active tab

- packages/theme/src/puik-tooltip.scss
> style: [Tooltip] - fix #407

- .github/ISSUE_TEMPLATE/---versioning-template.md
- RELEASE-NOTES-V2.md
- RELEASE.md
- docs/CHANGELOG.md
- docs/package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/locale/CHANGELOG.md
- packages/locale/package.json
- packages/puik/CHANGELOG.md
- packages/puik/package.json
- packages/resolver/CHANGELOG.md
- packages/resolver/package.json
- packages/tailwind-preset/CHANGELOG.md
- packages/tailwind-preset/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/utils/CHANGELOG.md
- packages/utils/package.json
- packages/web-components/CHANGELOG.md
- packages/web-components/components/tab-navigation.ts
- packages/web-components/package.json
- pnpm-lock.yaml
[chore] - bumped versions packages for release v2.4.0
> [chore] - bumped versions packages for release v2.4.0

- packages/components/alert/stories/alert.stories.ts
- packages/components/avatar/stories/avatar.stories.ts
- packages/components/breadcrumb/stories/breadcrumb.stories.ts
- packages/components/button/stories/button.stories.ts
- packages/components/chip/stories/chip.stories.ts
- packages/components/icon/stories/icon.stories.ts
- packages/components/modal/stories/modal.stories.ts
- packages/components/sidebar/stories/sidebar-group-item.stories.ts
- packages/components/sidebar/stories/sidebar-item.stories.ts
- packages/components/tag/stories/tag.stories.ts
> docs: update description for icon

- docs/storybook/stories/docs/VueJs.mdx
update **setup Vue** page ( fix #426)
> docs: [storybook-setup-vue] fix #426

- .gitignore
- docs/storybook/tsconfig.json
- docs/vitepress/tsconfig.json
- eslint.config.mjs
- package.json
- packages/components/textarea/src/textarea.ts
- packages/components/textarea/src/textarea.vue
- packages/components/textarea/test/textarea.spec.ts
- packages/components/tsconfig.json
- packages/locale/tsconfig.json
- packages/puik/tsconfig.json
- packages/resolver/tsconfig.json
- packages/tailwind-preset/tsconfig.json
- packages/utils/tsconfig.json
- packages/web-components/tsconfig.json
- playground/components.d.ts
- playground/tsconfig.json
- tsconfig.eslint.json
- tsconfig.json
-  fix #417
- **aditionnal changes** : [eslint-config] include components files, refacto tsconfig files for all packages
> feat: [textarea] emit blur event

- packages/components/input/src/input.ts
- packages/components/input/src/input.vue
- packages/components/input/stories/input.stories.ts
- packages/components/input/test/input.spec.ts
- packages/components/textarea/stories/textarea.stories.ts
- packages/theme/src/puik-input.scss
- playground/components.d.ts
> feat: [input] related #418 - add maxLength/minLength props

- packages/components/tooltip/src/tooltip.vue
- packages/components/tooltip/stories/tooltip.stories.ts
- packages/components/tooltip/test/tooltip.spec.ts
- packages/theme/src/animations.scss
- packages/theme/src/base.scss
- packages/theme/src/puik-skeleton-loader.scss
- packages/theme/src/puik-tooltip.scss
- playground/components.d.ts
see improvements details => #75
> feat: [tooltip] related #75 - refacto

- RELEASE.md
- docs/storybook/CHANGELOG.md
- docs/storybook/package.json
- docs/vitepress/CHANGELOG.md
- docs/vitepress/package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/locale/CHANGELOG.md
- packages/locale/package.json
- packages/puik/CHANGELOG.md
- packages/puik/package.json
- packages/resolver/CHANGELOG.md
- packages/resolver/package.json
- packages/tailwind-preset/CHANGELOG.md
- packages/tailwind-preset/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/utils/CHANGELOG.md
- packages/utils/package.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package.json
- playground/CHANGELOG.md
- playground/package.json
[chore] - bumped versions packages for release v2.5.0
> chore: bumped versions packages for release v2.5.0

- packages/components/modal/src/modal.ts
- packages/components/modal/src/modal.vue
- packages/components/modal/stories/modal.stories.ts
- packages/theme/src/puik-modal.scss
> feat: [modal][style][storybook] -

- .github/workflows/cd-publish-beta-release.yml
- .github/workflows/cd-publish-release.yml
- .github/workflows/chromatic.yml
- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
- upgrade pnpm to `10.9.0`
-  update pnpm-lock file
- update github workflows with the right package manager version
> chore: fix #448 

- packages/components/tag/src/tag.vue
- packages/components/tag/stories/tag.stories.ts
- packages/theme/src/puik-tag.css
- fix long text overflow (ellipsis)
- fix display tooltip for long content.
> feat: [Tag] fix #463

- packages/components/chip/src/chip.ts
- packages/components/chip/stories/chip.stories.ts
- packages/components/chip/test/chip.spec.ts
- packages/components/select/src/select.vue
- packages/theme/src/puik-chip.css
fix #466 :
- add border and border-radius
- text with font-weight medium
- :warning: **BC** : **remove small variant** (now the default variant corresponds to the old small variant) and create large variant.
> feat: [chip-style] fix #466 - apply new style

- docs/storybook/stories/docs/VueJs.mdx
- packages/components/breadcrumb/stories/breadcrumb.stories.ts
- packages/components/button/stories/button.stories.ts
- packages/components/notification-bar/stories/notification-bar.stories.ts
- packages/components/sortable-list/src/sortable-list.ts
- packages/components/sortable-list/stories/sortable-list.stories.ts
- packages/components/spinner-loader/stories/spinner-loader.stories.ts
- packages/components/switch/stories/switch.stories.ts
- packages/components/table/stories/table-search-input.stories.ts
- packages/components/table/stories/table.stories.ts
- packages/components/textarea/stories/textarea.stories.ts
- packages/components/tooltip/stories/tooltip.stories.ts
> docs: [storybook] - fix #474

- docs/storybook/assets/css/index.css
- packages/components/modal/src/modal.ts
- packages/components/modal/src/modal.vue
- packages/components/modal/stories/modal.stories.ts
- packages/theme/src/puik-modal.css
fix #297 :
- add props to handle the disabled state of buttons
- [storybook] update modal stories
- [style] fix modal title width
> feat: [modal] fix #297
